config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "/search" => "searches#search"
  get "book_search" => "homes#book_search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, presence: true, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def Book.book_search(keyword)
    Book.where("category LIKE?", "%#{keyword}%")
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord

  validates :message, length: {maximum: 140}

  belongs_to :user
  belongs_to :room

end

app/models/relationship.rb
class Relationship < ApplicationRecord

   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :messages, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  impressionist :actions=> [:show]


  def index
    @books = Book.all
    @book = Book.new
    @books = Book.all.order(params[:sort])
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    impressionist(@book, nil, unique: [:ip_address])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def book_search
    @book = Book.new
    @books = Book.book_search(params[:keyword])
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = UserRoom.create(user_id: current_user.id, room_id: @room.id)
    @entry2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if UserRoom.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @UserRooms = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    @user = User.find(params[:id])
    @currentUserRoom = UserRoom.where(user_id: current_user.id)
    @receiveUser = UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserRoom.each do |cu|
        @receiveUser.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @UserRoom = UserRoom.new
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment.html.erb
  <% book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    	<% end %>
    </tr>
  <% end %>

app/views/books/_form.html.erb
<%= form_with model:book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class:"form-control" %>
  </div>
  <div id="star" class="form-group">
    <%= f.label :rate %>
    <%= f.hidden_field :rate, class:"form-control" %>
  </div>
  <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn :  '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[rate]',

      half: true,
    });
  </script>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.category, book_search_path(keyword: book.category) %></td>
        <td class="favorite-btn_<%= book.id %>"><%= render "favorites/favorite-btn", book: book %></td>
        <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
       <td>閲覧数：<%= book.impressionist_count %></td>
        <td>
         <div id="rate_<%= book.id %>"></div>
          <script>
           $('#rate_<%= book.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= book.rate %>
           });
          </script>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>

  		<%= form_with model:@book, local: true do |f| %>
       <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control book_title' %>
       </div>
       <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: 'form-control book_body' %>
       </div>
       <div id="star" class="form-group">
        <%= f.hidden_field :rate, class:"form-control" %>
       </div>
       <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn :  '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'book[rate]',
          readOnly: true,
          half: true,
          score: <%= @book.rate %>
         });
       </script>
       <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
       </div>
      <% end %>

  		<%= link_to 'Show', book_path(@book) %> |
  		<%= link_to 'Back', books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: "created_at DESC") %> |
      <%= link_to "評価の高い順", books_path(sort: "rate DESC") %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
    <h2>Book detail</h2>
    <table class='table'>
  	 <tr>
  	  <td><%= link_to user_path(@book.user) do %>
       <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
       <%= @book.user.name %>
       <% end %>
      </td>
      <td><%= link_to @book.title, book_path(@book) %></td>
      <td><%= @book.body %></td>
      <td><%= @book.category %></td>
      <td class="favorite-btn_<%= @book.id %>"><%= render "favorites/favorite-btn", book: @book %></td>
      <td class= "comments-count">コメント数: <%= @book.book_comments.count %></td>
      <td>閲覧数：<%= @book.impressionist_count %></td>
      <td>
       <div id="rate_<%= @book.id %>"></div>
        <script>
        $('#rate_<%= @book.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @book.rate %>
         });
        </script>
      </td>
     <% if @book.user == current_user %>
      <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
      <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
     <% end %>
     </tr>
    </table>
    <table class = "book_comments">
     <%= render 'books/comment', book: @book,book_comment: @book_comment%>
    </table>
     <%= form_with model:[@book,@book_comment] do |f| %>
      <%= f.text_area :comment, size:"90x5" %><br>
      <%= f.submit '送信'%>
     <% end %>
    </div>
  </div>
 </div>

app/views/rooms/show.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-10">
      <% @UserRooms.each do |u| %>
       <a class="rooms-user-link" href="/users/<%= u.user.id %>">
         <h2> <%= u.user.name %>さんとのチャット</h2>
       </a>
      <% end %>
      <table class="table table-borderless">
        <% if @messages.present? %>
          <% @messages.each do |m| %>
            <% if m.user == current_user %>
              <tbody>
                <tr>
                  <td>
                    <p style = "text-align: left;"><%= m.user.name %></p>
                    <p style="text-align: left;"><%= m.message %><br><%= m.created_at.strftime("%Y-%m-%d %H:%M") %></p>
                  </td>
                </tr>
              </tbody>
            <% else %>
              <tbody>
                <tr>
                  <td>
                    <p style = "text-align: right;"><%= m.user.name %></p>
                    <p style="text-align: right;"><%= m.message %><br><%= m.created_at.strftime("%Y-%m-%d %H:%M") %></p>
                  </td>
                </tr>
              </tbody>
            <% end %>
          <% end %>
        <% end %>
      </table>
      <%= form_with model: @message, local: true do |f| %>
        <%= f.text_field :message %>
        <%= f.hidden_field :room_id, value: @room.id, class: "form-control" %>
        <%= f.submit "送信する", class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user) do %>
       <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user) do %>
       <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif current_user.following?(user) %>
    <%= link_to "フォロー外す",  user_relationships_path(user), method: :delete, class: "btn btn-primary btn-sm" %>
  <% else %>
    <%= link_to "フォローする",  user_relationships_path(user), method: :post, class: "btn btn-success btn-sm" %>
  <% end %>
 <%= render 'users/message', user: user %>
</div>

app/views/users/_message.html.erb
<% unless user.id == current_user.id %>
 <% if (current_user.following? user) && (user.following? current_user)  %>
  <% if @isRoom == true %>
    <a href="/rooms/<%= @roomId %>"> chatを始める</a>
  <% else %>
    <%= form_with model: @room, local: true do |f| %>
     <%= fields_for @UserRoom do |u| %>
      <%= u.hidden_field :user_id, value: user.id %>
     <% end %>
     <%= f.submit "チャットを始める" %>
    <% end %>
   <% end %>
 <% end %>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
        
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>