config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "/search" => "searches#search"
  get "book_search" => "homes#book_search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def perfect(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'perfect'
      perfect(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<div class = "container">
  <div class = "col-xs-12">
    <% if @model == 'user' %>
    <h3>Users search for "<%= @value %>"</h3>
    <table class = "table">
     <thead>
      <tr>
       <th>image</th>
       <th>name</th>
       <th colspan = "3"></th>
      </tr>
     </thead>
     <% @datas.each do |user| %>
     <tbody>
       <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
       <td><%= user.name %></td>
       <td><%= link_to 'Show', user_path(user) %></td>
     </tbody>
     <% end %>
    </table>
    <% elsif @model == 'book' %>
    <h3>Books search for "<%= @value %>"</h3>
    <table class = "table">
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan = "3"></th>
      </tr>
     </thead>
     <tbody>
      <% @datas.each do |book| %>
       <tr>
        <td><%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
       </tr>
      <% end %>
     </tbody>
    </table>
    <% else %>
    該当の書籍が見つかりませんでした
  <% end %>

  </div>
</div>